### PR TITLE
Resolve issues with error reporting

### LINKED ISSUE #72: Analytics error reports are not collected
### Describe the bug

The error collection does not work as intended. Please ensure the following lines can indeed produce the result and are called:
https://github.com/scandipwa/create-magento-app/blob/f4e0b5e01d303d1c8386f6403720b3f4392ab0be/build-packages/magento-scripts/lib/commands/start.js#L172
https://github.com/scandipwa/create-magento-app/blob/f4e0b5e01d303d1c8386f6403720b3f4392ab0be/build-packages/magento-scripts/lib/commands/start.js#L166

### PR DESCRIPTION
**Pull request by ejnshtein**
Fixes #72

### CODE REVIEW

File: build-packages/magento-scripts/lib/commands/start.js [hunk 1]
```diff
@@ -169,7 +169,11 @@ module.exports = (yargs) => {
                 process.exit(0);
             } catch (e) {
                 logger.error(e.message || e);
-                await googleAnalytics.trackError(e.message || e);
+                if (e && e.reportAnalytics) {
```
Comment (alfredsgenkins) [inline build-packages/magento-scripts/lib/commands/start.js:172]: This check will skip all non-CMA install errors. Please redo this check to skip if report analytics is set to false.

I.e. type errors will not be caught.

**Review by alfredsgenkins — CHANGES_REQUESTED** [review]

**Comment by alfredsgenkins** [comment]
This PR does not solve #72 as that bug was about an incorrect `process.env.GA_TRACKING_ID` environment variable. Analytics is sent to CSA not CMA.

**Comment by alfredsgenkins** [comment]
I generally think all errors (CMA and non CMA) must be collected, so I would not merge changes done in this PR anyway.

File: build-packages/magento-scripts/lib/commands/start.js (hunk 1 above)
Comment (ejnshtein) [reply build-packages/magento-scripts/lib/commands/start.js:172]: This is currently a draft PR, I was planning to make some custom error classes to prevent reporting of errors like "your docker is installed, restart your system" which is the only way of gracefully stopping task flow. So, something like type error will still be caught, as well as other non-cma errors.
So, this will be developed a little bit later, but my idea is like that.

**Comment by ejnshtein** [comment]
Some errors are not errors, that's the problem
